### ISSUE TITLE
Task not serializable

### ISSUE THREAD

**Issue by waynefoltaERI** [dmarcous/spark-beetweenness#1]
First, thanks for a great example! I really appreciate it, and it does exactly what I've been looking for.

Second, I copied/pasted your code into a larger project I'm working on, so this isn't directly an issue with what you did, but more of a question that you might be able to answer based on your experiences. When I run the (copy/pasted/modified) code, when it gets into the `Pregel` I get an error:

```
Exception in thread "main" org.apache.spark.SparkException: Task not serializable
    at org.apache.spark.util.ClosureCleaner$.ensureSerializable(ClosureCleaner.scala:304)
    at org.apache.spark.util.ClosureCleaner$.org$apache$spark$util$ClosureCleaner$$clean(ClosureCleaner.scala:294)
    at org.apache.spark.util.ClosureCleaner$.clean(ClosureCleaner.scala:122)
    at org.apache.spark.SparkContext.clean(SparkContext.scala:2055)
    at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1.apply(RDD.scala:707)
    at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1.apply(RDD.scala:706)
    at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:150)
    at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:111)
    at org.apache.spark.rdd.RDD.withScope(RDD.scala:316)
    at org.apache.spark.rdd.RDD.mapPartitions(RDD.scala:706)
    at org.apache.spark.graphx.impl.VertexRDDImpl.mapVertexPartitions(VertexRDDImpl.scala:96)
    at org.apache.spark.graphx.impl.GraphImpl.mapVertices(GraphImpl.scala:132)
    at org.apache.spark.graphx.Pregel$.apply(Pregel.scala:122)
    at Main$KBetweenness$2$.createKGraphlets(Main.scala:672)
    at Main$KBetweenness$2$.run(Main.scala:636)
    at Main$.do_spark_3$1(Main.scala:783)
    at Main$.main(Main.scala:801)
    at Main.main(Main.scala)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Caused by: java.io.NotSerializableException: Main$KBetweenness$2$
Serialization stack:
    - object not serializable (class: Main$KBetweenness$2$, value: Main$KBetweenness$2$@4fc142ec)
    - field (class: Main$KBetweenness$2$$anonfun$createKGraphlets$1, name: $outer, type: class Main$KBetweenness$2$)
    - object (class Main$KBetweenness$2$$anonfun$createKGraphlets$1, <function3>)
    - field (class: org.apache.spark.graphx.Pregel$$anonfun$1, name: vprog$1, type: interface scala.Function3)
    - object (class org.apache.spark.graphx.Pregel$$anonfun$1, <function2>)
    - field (class: org.apache.spark.graphx.impl.GraphImpl$$anonfun$5, name: f$1, type: interface scala.Function2)
    - object (class org.apache.spark.graphx.impl.GraphImpl$$anonfun$5, <function1>)
    - field (class: org.apache.spark.graphx.impl.VertexRDDImpl$$anonfun$1, name: f$1, type: interface scala.Function1)
    - object (class org.apache.spark.graphx.impl.VertexRDDImpl$$anonfun$1, <function1>)
    at org.apache.spark.serializer.SerializationDebugger$.improveException(SerializationDebugger.scala:40)
    at org.apache.spark.serializer.JavaSerializationStream.writeObject(JavaSerializer.scala:47)
    at org.apache.spark.serializer.JavaSerializerInstance.serialize(JavaSerializer.scala:101)
    at org.apache.spark.util.ClosureCleaner$.ensureSerializable(ClosureCleaner.scala:301)
    ... 22 more
```

I'm feeding it a graph from `GraphGenerators.logNormalGraph` if that makes any difference. Any thoughts off the top of your head?

Thanks!

**Comment by wfolta** [comment]
OK, I think I found the solution. Change the `KBetweenness` object declaration to:

`object KBetweenness extends Serializable`

**Comment by dmarcous** [comment]
Hi Wayne,

First of all thanks for using, hope it helps :)

Glad you already got that covered. It makes sense that if you try and
activate the KBetweenness function inside a map / reduce operation in Spark
then it has to be Serializable (cause it needs to move the code for the
function between machines).

Nice catch on the solution, you are welcome to contact again if you run to
anymore trouble!

Regards,
Daniel Marcous.

**Comment by waynefoltaERI** [comment]
Thanks, I'll close this out.
